services:

  blacklists:
    build: blacklists
    ports:
      - "3000:3000"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=awseb-e-vwaujujx7u-stack-awsebrdsdatabase-hfesriedqdpc.ct080mawcvct.us-east-2.rds.amazonaws.com
      - DB_PORT=5432
      - DB_NAME=blacklists
      - TOKEN=secret


